### ISSUE TITLE
release to GPlay with minor but important improvements

### ISSUE THREAD

**Issue by vidma** [vidma/aac-speech-android#47]
- [x] add an option in the settings whether to speak each icon....
- [ ] larger back button
- [x] icon extaction is running each time!? check the hash thingy; shouldnt be cancelable, right...
- [ ] **make tableview in main window scroll-auto -- like this the tabs will fit even on tiny devices...**
- [x] **describe spc colors in docs: fr**
- [x] test it: fr
- [x] remove extra debugging
  - debug mode
  - db creator?
- [ ] add link to change language - system settings
- [x] build the apk
- [x] test on tablet
- [x] test upgrade from earlier version (G Play)
- [x] release to production
- [x] update screenshots
- [ ] add a video

Summary:
- updated UI: added tabs in category view, improved search (google gesture search removed temporarily)
- add tablet

**Skip:**
- [ ] last phrases, todo: need display...
- [ ] **add word_clean (w/o to), so search might work faster?**
- [ ] catg. adverb of place is poor
- [ ] in app purchases - donate
- [ ] gesture search don't work well
- [ ] phrase history is dead (remove until next release)
- [ ] reorganize icons? 
  - show first: time?
  - move lower: adv.place - don't work well anyway..., dot? is it so important?
  - time icon - black background?

Done:
- [x] apply new fancy beautiful action bar style
  - gray/less intence border bettween search and category?
- [x] "censorship"
- [x] large screen & landscape-mode and better tablet support
- [x] on phones make it clear that second "screen" exists
- [x] simplify how datafiles are shipped
- [x] minor improvements to french & english tagging of items -- old commit by ...
- [x] improve the buttons: fixed in #48
  -  back button: category (it's not displayed correctly)
  - delete button
- [x] label do not fit - fix: 60a5f9259d1916fe45510203c00d5c73303ae3c2
- [x] refactor the code in PR #49
- [x]  gridview: fast scrolling + first letter display
- [x] in english, eliminate the "to" when sorting - add column?
  - P.S. only a hack for now...
- [x] enable search in gridview? fixed in #50
- [x] use UUID so updates can be performed?! fixed in #51
- [x] **optional: storing 4000 files in assets is increasing memory use ~7-9MB extra (35%+)**
  - e.g. store zip file + hash, check hash & extract to data dir on first load.
- [x] search widget is crap (the one used if  Gesture search is absent)
  - this should actually use standard search functionality plus fast scroll
  - gridview vs listview vs searchview?
  - TODO: searching over all (no category)
- [x] seem fine now: detecting memory leaks..
- [x] improve docs - incl. describe SPC colors
  - TODO: translate to french
- [x] smaller "inf"/all icon in category
- [x] speak each icon on low voice when added
- [x] **add basic tabs: for now: all, recently used**
  -  phrase history is crap and broken, so maybe add recently used tab
    - I got rid of the recently used (cursor), as it was messing up the fastscroll...
  -  favourite phrases...!!! (next release)? 
  - display important icons first (!)
    - TODO: in future may allow to mark an icon as important!
- [x] describe spc colors in docs: en
- [x] updated a couple of icons...
- [x] once categoty selected - hide not important actions, so more space is available for icons and UI is less overwhelming, with tabs etc...
  - leave only: search, maybe info..?
- [x] optional: ease the dependency installation
- [x] update the pics
